version: '3.8'

services:
  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=api-rest
    depends_on:
      - mariadb
    networks:
      - bdd-network
      - app-network
    command: >
      sh -c "
        npx sequelize-cli db:migrate && npm start
      "

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=api-rest
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bdd-network

volumes:
  db_data:

networks:
  bdd-network:
  app-network:
