services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    environment:
      - APP_HOST=${APP_HOST}
      - PORT=${PORT}
    networks:
      - app-network
    restart: unless-stopped

  api:
    build: .
    container_name: api
    expose:
      - "${PORT}"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    depends_on:
      - mariadb
    networks:
      - app-network
    command: >
      sh -c "
        npx sequelize-cli db:migrate && npm start
      "

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
